const CONSTANTES = {
    REGISTRO: 'REGISTRO',
    LOGIN: 'LOGIN',
    ESTABLECER_SESION: 'ESTABLECER_SESION',
    CERRAR_SESION:'CERRAR_SESION',
    ESTABLECER_IMAGEN_PERFIL: 'ESTABLECER_IMAGEN_PERFIL',
    LIMPIAR_IMAGEN_PERFIL: 'LIMPIAR_IMAGEN_PERFIL'
}

export default CONSTANTES