const CONSTANTES = {
    REGISTRO: 'REGISTRO',
    LOGIN: 'LOGIN',
    ESTABLECER_SESION: 'ESTABLECER_SESION',
    CERRAR_SESION:'CERRAR_SESION',
    ESTABLECER_IMAGEN_PERFIL: 'ESTABLECER_IMAGEN_PERFIL',
    LIMPIAR_IMAGEN_PERFIL: 'LIMPIAR_IMAGEN_PERFIL',
    CONFIRMAR_CAMBIOS_PERFIL: 'CONFIRMAR_CAMBIOS_PERFIL',
    CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dtgnejqoj/image/upload',
    CLOUDINARY_PRESET: 'aa6gfbfy',
    LOGIN_FACEBOOK: 'LOGIN_FACEBOOK',
    IMAGEN_SELECCIONADA: 'IMAGEN_SELECCIONADA',
    SUBIR_IMAGEN: 'SUBIR_IMAGEN',
    CONSEGUIR_USUARIO: 'CONSEGUIR_USUARIO',
    GUARDAR_DATOS_USER: 'GUARDAR_DATOS_USER',
    DESCARGAR_PUBLICACIONES: 'DESCARGAR_PUBLICACIONES',
    OBTENER_PUBLICACIONES: 'OBTENER_PUBLICACIONES',
    OBTENER_AUTORES: 'OBTENER_AUTORES',
    LIMPIAR_USUARIO: 'LIMPIAR_USUARIO',
    CONSEGUIR_PUBLICACIONES: 'CONSEGUIR_PUBLICACIONES',
    PUBLICACIONES_PERFIL_AJENO: 'PUBLICACIONES_PERFIL_AJENO',
    DAR_LIKE: 'DAR_LIKE',
    QUITAR_LIKE: 'QUITAR_LIKE',
    CONSEGUIR_USUARIOS_LIKES: 'CONSEGUIR_USUARIOS_LIKES',
    PONER_USUARIOS_LIKE: 'PONER_USUARIOS_LIKE',
    CONSEGUIR_UID_LIKES: 'CONSEGUIR_UID_LIKES',
    ERROR_EN_LOGIN: 'ERROR_EN_LOGIN',
    ERROR_EN_SIGNUP: 'ERROR_EN_SIGNUP',
    BORRAR_IMAGEN: 'BORRAR_IMAGEN',
    ENVIAR_COMENTARIO: 'ENVIAR_COMENTARIO',
    DESCARGAR_COMENTARIOS: 'DESCARGAR_COMENTARIOS',
    COMENTARIOS_STORE_TODOS: 'COMENTARIOS_STORE_TODOS',
    COMENTARIOS_STORE_UNO: 'COMENTARIOS_STORE_UNO'



}

export default CONSTANTES