const CONSTANTES = {
    REGISTRO: 'REGISTRO',
    LOGIN: 'LOGIN',
    ESTABLECER_SESION: 'ESTABLECER_SESION',
    CERRAR_SESION:'CERRAR_SESION',
    ESTABLECER_IMAGEN_PERFIL: 'ESTABLECER_IMAGEN_PERFIL',
    LIMPIAR_IMAGEN_PERFIL: 'LIMPIAR_IMAGEN_PERFIL',
    CONFIRMAR_CAMBIOS_PERFIL: 'CONFIRMAR_CAMBIOS_PERFIL',
    CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dtgnejqoj/image/upload',
    CLOUDINARY_PRESET: 'aa6gfbfy',
    LOGIN_FACEBOOK: 'LOGIN_FACEBOOK',
    IMAGEN_SELECCIONADA: 'IMAGEN_SELECCIONADA',
    SUBIR_IMAGEN: 'SUBIR_IMAGEN',
    CONSEGUIR_USUARIO: 'CONSEGUIR_USUARIO',
    GUARDAR_DATOS_USER: 'GUARDAR_DATOS_USER'
}

export default CONSTANTES